---
- name: Configure SSG
  hosts: all
  tasks:
    - name: Edit SSH Config
      blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          MaxAuthTries 3
          Banner /etc/motd
          X11Forwarding no
      notify: restart ssh
  handlers:
    - name: restart ssh
      service:
        name: sshd
        state: restarted
