---
- name: first play
  hosts: all
  tasks:
    - name: create a new file
      file:
        path: /tmp/foo.txt
        mode: 0664
        owner: ansible
        state: touch
    - name: create groups
      import_tasks: group-tasks.yml
