---
- name: Install NFS on centos
  hosts: all
  tasks:
   - name: Install NFS
     block:
        - name: Install NFS utils
          yum:
            name: nfs-utils
            state: latest
          when:
            ansible_facts.distribution == "CentOS"
