---
- name: Configure a NIC
  hosts: ansible1
  tasks:
    - name: Configure enp0s3
      nmcli:
        ifname: enp0s3
        conn_name: enp0s3
        type: ethernet
        ip4: 192.168.0.66
        dns4:
          - 8.8.8.8
          - 8.8.4.4
        state: present

    - name: Set hostname
      hostname: 
        name: ansible1.localdomain
    
    - name: Enable http/https 
      firewalld:
        zone: public
        service: "{{ item }}"
        permanent: yes
        state: enabled
      loop: [http, https ]
      notify: restart firewalld

  handlers:
    - name: restart firewalld
      service:
        name: firewalld
        state: restarted
