---
- name: playbook to do somethigc 
  hosts: node1
  tasks:
    - name: Touch the same file, but add/remove some permissions
      file:
        path: /etc/foo.conf2
        state: touch
        mode: u+rw,g-wx,o-rwx

    - name: Remove file
      file:
        path: /etc/foo.conf
        state: absent

