- name: Test variables
  hosts: node1
  vars_files: myvars.yml
  vars:
    fav_color: green
  tasks:
    - name: Show color
      debug:
        msg: My favourite color is {{ fav_color }}
    - name: Show ports
      debug:
        msg: My chosen ports are {{ ports }}
    - name: Show port
      debug:
        msg: My chosen ports is {{ ports[0] }}
    - name: show bog uuid
      debug:
        msg: UID of bob is {{ users.bob.uid }}
