---
- name: Accessing Vaults in Playbooks
  hosts: ansible3
  vars_files: 
    - web-secrets.yml
    - db-secrets.yml
  tasks:
    - name: Show secret value
      debug:
        msg: "{{secret1}}"
    - name: Show secret2 value
      debug:
        msg: "{{ secret2}}"
